// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'covid_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CovidDetail _$CovidDetailFromJson(Map<String, dynamic> json) {
  return CovidDetail(
    idAngka: json['id_angka'] as String,
    isSopStakeholder: json['is_sop_stakeholder'] as String,
    lastUpdate: json['last_update'] as String,
    namaLengkap: json['nama_lengkap'] as String,
    id: json['id'] as int,
    keterangan: json['keterangan'] as String,
    campaign: json['campaign'] as String,
    grandTotal: json['grand_total'] as int,
    grandTotalColor: json['grand_total_color'] as int,
    isCampaign: json['is_campaign'] as String,
    isReview: json['is_review'] as String,
    isSopKaryawan: json['is_sop_karyawan'] as String,
    isSopMitra: json['is_sop_mitra'] as String,
    isSopPelanggan: json['is_sop_pelanggan'] as String,
    isSopSupplier: json['is_sop_supplier'] as String,
    isSosialisasi: json['is_sosialisasi_karyawan'] as String,
    isSosialisasiMitra: json['is_sosialisasi_mitra'] as String,
    isSosialisasiplgn: json['is_sosialisasi_pelanggan'] as String,
    isSosialisasiStake: json['is_sosialisasi_stakeholder'] as String,
    isSosialisasiSupplier: json['is_sosialisasi_supplier'] as String,
    isTaskForce: json['is_taskforce'] as String,
    jumlahProtokol: json['jumlah_protokol'] as int,
    jumlahProtokolColor: json['jumlah_protokol_color'] as int,
    jumlahSosialisasi: json['jumlah_sosialisasi'] as int,
    jumlahTaskforce: json['jumlah_taskforce'] as int,
    jumlahTaskforceColor: json['jumlah_taskforce_color'] as int,
    review: json['review'] as String,
    reviewFile: json['review_file'] as String,
    sopKaryawan: json['sop_karyawan'] as String,
    sopMitra: json['sop_mitra'] as String,
    sopPelanggan: json['sop_pelanggan'] as String,
    sopStakeholder: json['sop_stakeholder'] as String,
    sopSupplier: json['sop_supplier'] as String,
    sosialisasi: json['sosialisasi_karyawan'] as String,
    sosialisasiMitra: json['sosialisasi_mitra'] as String,
    sosialisasiplgn: json['sosialisasi_pelanggan'] as String,
    sosialisasiStake: json['sosialisasi_stakeholder'] as String,
    sosialisasiSupplier: json['sosialisasi_supplier'] as String,
    taskForce: json['taskforce'] as String,
  );
}

Map<String, dynamic> _$CovidDetailToJson(CovidDetail instance) =>
    <String, dynamic>{
      'grand_total': instance.grandTotal,
      'last_update': instance.lastUpdate,
      'jumlah_taskforce': instance.jumlahTaskforce,
      'jumlah_protokol': instance.jumlahProtokol,
      'jumlah_sosialisasi': instance.jumlahSosialisasi,
      'grand_total_color': instance.grandTotalColor,
      'jumlah_taskforce_color': instance.jumlahTaskforceColor,
      'jumlah_protokol_color': instance.jumlahProtokolColor,
      'id': instance.id,
      'id_angka': instance.idAngka,
      'nama_lengkap': instance.namaLengkap,
      'taskforce': instance.taskForce,
      'is_taskforce': instance.isTaskForce,
      'sop_karyawan': instance.sopKaryawan,
      'is_sop_karyawan': instance.isSopKaryawan,
      'sop_pelanggan': instance.sopPelanggan,
      'is_sop_pelanggan': instance.isSopPelanggan,
      'sop_supplier': instance.sopSupplier,
      'is_sop_supplier': instance.isSopSupplier,
      'sop_mitra': instance.sopMitra,
      'is_sop_mitra': instance.isSopMitra,
      'sop_stakeholder': instance.sopStakeholder,
      'is_sop_stakeholder': instance.isSopStakeholder,
      'sosialisasi_karyawan': instance.sosialisasi,
      'is_sosialisasi_karyawan': instance.isSosialisasi,
      'sosialisasi_pelanggan': instance.sosialisasiplgn,
      'is_sosialisasi_pelanggan': instance.isSosialisasiplgn,
      'sosialisasi_supplier': instance.sosialisasiSupplier,
      'is_sosialisasi_supplier': instance.isSosialisasiSupplier,
      'sosialisasi_mitra': instance.sosialisasiMitra,
      'is_sosialisasi_mitra': instance.isSosialisasiMitra,
      'sosialisasi_stakeholder': instance.sosialisasiStake,
      'is_sosialisasi_stakeholder': instance.isSosialisasiStake,
      'campaign': instance.campaign,
      'is_campaign': instance.isCampaign,
      'review': instance.review,
      'review_file': instance.reviewFile,
      'is_review': instance.isReview,
      'keterangan': instance.keterangan,
    };
