// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hc_summary.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

HcSummary _$HcSummaryFromJson(Map<String, dynamic> json) {
  return HcSummary(
    totalBumnCucu: json['total_bumn_cucu'] as int,
    totalBumnAp: json['total_bumn_ap'] as int,
    selectedTalentSource: json['talent_sources_selected'] as int,
    nominatedTalentSource: json['talent_sources_nominated'] as int,
    eligibleTalentSource: json['talent_sources_eligible'] as int,
    readyTalentSource: json['talent_sources_ready'] as int,
    dekomAnakPerempuan: json['boc_anak_perempuan'] as int,
    dekomAnakLaki: json['boc_anak_laki_laki'] as int,
    bodAnakPerempuan: json['bod_anak_perempuan'] as int,
    bodAnakLaki: json['bod_anak_laki_laki'] as int,
    dekomCucuPerempuan: json['boc_cucu_perempuan'] as int,
    dekomCucuLaki: json['boc_cucu_laki_laki'] as int,
    bodCucuPerempuan: json['bod_cucu_perempuan'] as int,
    bodCucuLaki: json['bod_cucu_laki_laki'] as int,
    jumlahKomisarisAp: json['jumlah_komisaris_ap'] as int,
    jumlahDireksiAp: json['jumlah_direksi_ap'] as int,
    jumlahKomisarisCucu: json['jumlah_komisaris_cucu'] as int,
    jumlahDireksiCucu: json['jumlah_direksi_cucu'] as int,
    totalPegawai: json['total_pegawai'] as int,
    pegawaiTetap: json['pegawai_tetap'] as int,
    pegawaiKontrak: json['pegawai_kontrak'] as int,
    laki: json['laki_laki'] as int,
    perempuan: json['perempuan'] as int,
    jumlahKomisaris: json['jumlah_komisaris'] as int,
    jumlahDireksi: json['jumlah_direksi'] as int,
    totalBumn: json['total_bumn_induk'] as int,
    umurA: json['umur_a'] as int,
    umurB: json['umur_b'] as int,
    umurC: json['umur_c'] as int,
    umurD: json['umur_d'] as int,
    umurE: json['umur_e'] as int,
    bocAvgInDays: json['boc_avg_indays'] as int,
    bocLaki: json['boc_laki_laki'] as int,
    bocLessOneYear: json['boc_less_one_year'] as int,
    bocMoreFourYear: json['boc_more_than_five_year'] as int,
    bocOneTwoYear: json['boc_one_two_years'] as int,
    bocPerempuan: json['boc_perempuan'] as int,
    bocThreeFourYear: json['boc_three_four_years'] as int,
    bocTotal: json['boc_total'] as int,
    bocTwoThreeYear: json['boc_two_three_years'] as int,
    bocUmurA: json['boc_umur_a'] as int,
    bocUmurB: json['boc_umur_b'] as int,
    bocUmurC: json['boc_umur_c'] as int,
    bocUmurD: json['boc_umur_d'] as int,
    bocUmurE: json['boc_umur_e'] as int,
    bod1TotalHome: json['jumlah_20_percents_bod1'] as int,
    bod1AvgInDays: json['bod1_avg_indays'] as int,
    bod1Laki: json['bod1_laki_laki'] as int,
    bod1LessOneYear: json['bod1_less_one_year'] as int,
    bod1MoreFourYear: json['bod1_more_than_five_year'] as int,
    bod1OneTwoYear: json['bod1_one_two_years'] as int,
    bod1Perempuan: json['bod1_perempuan'] as int,
    bod1ThreeFourYear: json['bod1_three_four_years'] as int,
    bod1Total: json['bod1_total'] as int,
    bod1TwoThreeYear: json['bod1_two_three_years'] as int,
    bod1UmurA: json['bod1_umur_a'] as int,
    bod1UmurB: json['bod1_umur_b'] as int,
    bod1UmurC: json['bod1_umur_c'] as int,
    bod1UmurD: json['bod1_umur_d'] as int,
    bod1UmurE: json['bod1_umur_e'] as int,
    bodAvgInDays: json['bod_avg_indays'] as int,
    bodLaki: json['bod_laki_laki'] as int,
    bodLessOneYear: json['bod_less_one_year'] as int,
    bodMoreFourYear: json['bod_more_than_five_year'] as int,
    bodOneTwoYear: json['bod_one_two_years'] as int,
    bodPerempuan: json['bod_perempuan'] as int,
    bodThreeFourYear: json['bod_three_four_years'] as int,
    bodTotal: json['bod_total'] as int,
    bodTwoThreeYear: json['bod_two_three_years'] as int,
    bodUmurA: json['bod_umur_a'] as int,
    bodUmurB: json['bod_umur_b'] as int,
    bodUmurC: json['bod_umur_c'] as int,
    bodUmurD: json['bod_umur_d'] as int,
    bodUmurE: json['bod_umur_e'] as int,
    totalTalentResources: json['total_talent_sources'] as int,
  );
}

Map<String, dynamic> _$HcSummaryToJson(HcSummary instance) => <String, dynamic>{
      'total_pegawai': instance.totalPegawai,
      'pegawai_tetap': instance.pegawaiTetap,
      'pegawai_kontrak': instance.pegawaiKontrak,
      'laki_laki': instance.laki,
      'perempuan': instance.perempuan,
      'jumlah_komisaris': instance.jumlahKomisaris,
      'jumlah_direksi': instance.jumlahDireksi,
      'total_bumn_induk': instance.totalBumn,
      'umur_a': instance.umurA,
      'umur_b': instance.umurB,
      'umur_c': instance.umurC,
      'umur_d': instance.umurD,
      'umur_e': instance.umurE,
      'jumlah_20_percents_bod1': instance.bod1TotalHome,
      'bod1_total': instance.bod1Total,
      'bod1_perempuan': instance.bod1Perempuan,
      'bod1_laki_laki': instance.bod1Laki,
      'bod1_umur_a': instance.bod1UmurA,
      'bod1_umur_b': instance.bod1UmurB,
      'bod1_umur_c': instance.bod1UmurC,
      'bod1_umur_d': instance.bod1UmurD,
      'bod1_umur_e': instance.bod1UmurE,
      'bod1_avg_indays': instance.bod1AvgInDays,
      'bod1_less_one_year': instance.bod1LessOneYear,
      'bod1_one_two_years': instance.bod1OneTwoYear,
      'bod1_two_three_years': instance.bod1TwoThreeYear,
      'bod1_three_four_years': instance.bod1ThreeFourYear,
      'bod1_more_than_five_year': instance.bod1MoreFourYear,
      'boc_total': instance.bocTotal,
      'boc_perempuan': instance.bocPerempuan,
      'boc_laki_laki': instance.bocLaki,
      'boc_umur_a': instance.bocUmurA,
      'boc_umur_b': instance.bocUmurB,
      'boc_umur_c': instance.bocUmurC,
      'boc_umur_d': instance.bocUmurD,
      'boc_umur_e': instance.bocUmurE,
      'boc_avg_indays': instance.bocAvgInDays,
      'boc_less_one_year': instance.bocLessOneYear,
      'boc_one_two_years': instance.bocOneTwoYear,
      'boc_two_three_years': instance.bocTwoThreeYear,
      'boc_three_four_years': instance.bocThreeFourYear,
      'boc_more_than_five_year': instance.bocMoreFourYear,
      'bod_total': instance.bodTotal,
      'bod_perempuan': instance.bodPerempuan,
      'bod_laki_laki': instance.bodLaki,
      'bod_umur_a': instance.bodUmurA,
      'bod_umur_b': instance.bodUmurB,
      'bod_umur_c': instance.bodUmurC,
      'bod_umur_d': instance.bodUmurD,
      'bod_umur_e': instance.bodUmurE,
      'bod_avg_indays': instance.bodAvgInDays,
      'bod_less_one_year': instance.bodLessOneYear,
      'bod_one_two_years': instance.bodOneTwoYear,
      'bod_two_three_years': instance.bodTwoThreeYear,
      'bod_three_four_years': instance.bodThreeFourYear,
      'bod_more_than_five_year': instance.bodMoreFourYear,
      'jumlah_komisaris_ap': instance.jumlahKomisarisAp,
      'jumlah_direksi_ap': instance.jumlahDireksiAp,
      'jumlah_komisaris_cucu': instance.jumlahKomisarisCucu,
      'jumlah_direksi_cucu': instance.jumlahDireksiCucu,
      'boc_cucu_perempuan': instance.dekomCucuPerempuan,
      'boc_cucu_laki_laki': instance.dekomCucuLaki,
      'bod_cucu_perempuan': instance.bodCucuPerempuan,
      'bod_cucu_laki_laki': instance.bodCucuLaki,
      'boc_anak_perempuan': instance.dekomAnakPerempuan,
      'boc_anak_laki_laki': instance.dekomAnakLaki,
      'bod_anak_perempuan': instance.bodAnakPerempuan,
      'bod_anak_laki_laki': instance.bodAnakLaki,
      'talent_sources_selected': instance.selectedTalentSource,
      'talent_sources_nominated': instance.nominatedTalentSource,
      'talent_sources_eligible': instance.eligibleTalentSource,
      'talent_sources_ready': instance.readyTalentSource,
      'total_bumn_cucu': instance.totalBumnCucu,
      'total_bumn_ap': instance.totalBumnAp,
      'total_talent_sources': instance.totalTalentResources,
    };
