// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'legal_item.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LegalItem _$LegalItemFromJson(Map<String, dynamic> json) {
  return LegalItem(
    id: json['id'] as int,
    nomorPerkaraOld: json['nomor_perkara'] as String,
    bumn: json['bumn'] as String,
    createdAt: json['created_at'] as String,
    keterangan: json['keterangan'] as String,
    kota: json['kota'] as String,
    tahun: json['tahun'] as int,
    bumn_id: json['bumn_id'] as String,
    nomorPerkara: json['no_perkara'] as String,
    nomorSkk: json['no_skk'] as String,
    objekGugatan: json['objek_gugatan'] as String,
    penggugat: json['penggugat'] as String,
    asdep: json['asdep'] as String,
    cluster_bumn: json['cluster_bumn'] as String,
    cluster_covid: json['cluster_covid'] as String,
    cluster_lama: json['cluster_lama'] as String,
    id_angka: json['id_angka'] as String,
    tergugat: json['tergugat'] as String,
    updatedAt: json['updated_at'] as String,
    jenis_perkara: json['jenis_perkara'] as String,
    kelas_bumn: json['kelas_bumn'] as String,
    kode_asdep: json['kode_asdep'] as String,
    level: json['level'] as int,
    logobumn: json['logobumn'] as String,
    nama_lengkap: json['nama_lengkap'] as String,
    nama_pendek: json['nama_pendek'] as String,
    objek_perkara: json['objek_perkara'] as String,
    petitum: json['petitum'] as String,
    progress: json['progress'] as String,
    sektor_bumn: json['sektor_bumn'] as String,
    skala_jabatan_bumn: json['skala_jabatan_bumn'] as String,
    tempat_perkara: json['tempat_perkara'] as String,
    tingkat_perkara: json['tingkat_perkara'] as String,
    top_bumn: json['top_bumn'] as String,
    wamen_bumn: json['wamen_bumn'] as String,
    wamen_covid: json['wamen_covid'] as String,
    wamen_lama: json['wamen_lama'] as String,
  );
}

Map<String, dynamic> _$LegalItemToJson(LegalItem instance) => <String, dynamic>{
      'id': instance.id,
      'nomor_perkara': instance.nomorPerkaraOld,
      'no_perkara': instance.nomorPerkara,
      'no_skk': instance.nomorSkk,
      'jenis_perkara': instance.jenis_perkara,
      'tingkat_perkara': instance.tingkat_perkara,
      'penggugat': instance.penggugat,
      'tergugat': instance.tergugat,
      'objek_perkara': instance.objek_perkara,
      'objek_gugatan': instance.objekGugatan,
      'petitum': instance.petitum,
      'keterangan': instance.keterangan,
      'bumn_id': instance.bumn_id,
      'bumn': instance.bumn,
      'kota': instance.kota,
      'tempat_perkara': instance.tempat_perkara,
      'progress': instance.progress,
      'tahun': instance.tahun,
      'id_angka': instance.id_angka,
      'nama_lengkap': instance.nama_lengkap,
      'nama_pendek': instance.nama_pendek,
      'cluster_bumn': instance.cluster_bumn,
      'wamen_bumn': instance.wamen_bumn,
      'sektor_bumn': instance.sektor_bumn,
      'kelas_bumn': instance.kelas_bumn,
      'top_bumn': instance.top_bumn,
      'skala_jabatan_bumn': instance.skala_jabatan_bumn,
      'asdep': instance.asdep,
      'logobumn': instance.logobumn,
      'cluster_covid': instance.cluster_covid,
      'wamen_covid': instance.wamen_covid,
      'cluster_lama': instance.cluster_lama,
      'wamen_lama': instance.wamen_lama,
      'level': instance.level,
      'kode_asdep': instance.kode_asdep,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
    };
