
class Strings {

  static String getString(String key) => _strings[key];

  static const _strings = {
    "WelcomePage.Title": "Kementerian BUMN\nExecutive Information Dashboard",
    "WelcomePage.StartHere": "Mulai disini",
    "WelcomePage.LoginButtonText": "Masuk",
    "WelcomePage.EmailLabel": "Email",
    "WelcomePage.EmailHint": "Email Anda",
    "WelcomePage.PasswordLabel": "Kata Sandi",
    "WelcomePage.PasswordHint": "Kata Sandi Anda",
    "WelcomePage.EmailError": "Email Anda salah",
    "WelcomePage.PasswordError": "Password harus lebih panjang dari 4 karakter",
    "LoadingDialog.Title": "Mohon tunggu...",
    "Messages.OK": "OK",
    "LoginFailedDialog.Title": "Login gagal",
    "LoginFailedDialog.DefaultMessage": "Email or Kata sandi salah",
    "LoginSuccessDialog.Title": "Login sukses",
    "LoginSuccessDialog.Message": "Anda telah berhasil masuk",
    "HomePage.Salutation": "Hi, ",
    "HomePage.Title": "Executive Information Dashboard",
    "HomePage.SubTitle": "Temukan informasi terkait BUMN disini",
    "HomePage.BusinessPortfolio": "Business Portfolio",
    "HomePage.Finance": "Finance",
    "HomePage.CSR": "CSR",
    "HomePage.Legal": "Legal",
    "HomePage.Event": "Event",
    "HomePage.HumanCapital": "Human Capital",
    "HomePage.PMO": "PMO",
    "FeatureNotAvailableDialog.Title": "Fitur belum tersedia",
    "FeatureNotAvailableDialog.Message": "Mohon maaf, fitur belum tersedia pada versi ini.",
    "BusinessPortfolioPage.Title": "Business Portfolio",
    "BusinessPortfolioPage.JenisBumn": "BUMN by Ownership",
    "BusinessPortfolioPage.TotalBumn": "Profile BUMN",
    "BusinessPortfolioPage.SectorBumn": "BUMN by Sector",
    "BusinessPortfolioPage.ClusterBumn": "BUMN by Cluster",
    "BusinessPortfolioPage.ClassBumn": "BUMN by Class",
    "DBJenisBumnPage.Title": "BUMN by Ownership",
    "TotalBumnPage.Title": "Daftar BUMN",
    "Messages.DefaultApiError": "Terjadi kesalahan pada sistem",
    "SektorBumnPage.Title": "BUMN by Sector",
    "KelasBumnPage.Title": "BUMN by Class",
    "ClusterBumnPage.Title": "BUMN by Cluster",
    "PosisiKeuanganPage.Title": "Posisi Keuangan",
    "LabaRugiPage.Title": "Laba Rugi",
    "CapexPage.Title": "Capex",
    "RevenuePage.Title": "Revenue",
    "LoanPage.Title": "Loan",
    "EbitdaPage.Title": "EBITDA",
    "APBNPage.Title": "Kontribusi Pada Negara",
    "DividenPage.Title": "Dividen",
    "PajakPage.Title": "Pajak",
    "PnbpPage.Title": "PNBP",
    "LegalPage.Title": "Legal",
    "CaseIssuesPage.Title": "Case & Issues",
    "CaseCategoryPage.Title": "Case by Category",
    "CaseStatusPage.Title": "Case by Status",
    "CsrPage.Title": "CSR",
    "ProgramKemitraanPage.Title": "Program Kemitraan",
    "RealisasiDanaPage.Title": "Realisasi Dana",
    "SektorPenyaluranPage.Title": "Sektor Penyaluran",
  };

}